### ISSUE TITLE
Do you have a node to run inspect command?

### ISSUE THREAD

**Issue by lurais** [allada/eth-archive-snapshot#3]
Hello , I want to analyze the storage of the data space in eth, and want to know percentage of each part,do you have a node to run the command 'geth db inspect' (cannot be executed simultaneously as another geth is running)? Example output: https://github.com/ethereum/go-ethereum/pull/25896#issue-1391842360

**Comment by allada** [comment]
This snapshot uses `erigon`, not `geth`.
